import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        ignores: ["out/**", "vscode.d.ts", "vscode.proposed.*", "webpack.config.js"],
    },
    {
        files: ["src/**/*.ts"],
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "module",
        },
        rules: {
            "@typescript-eslint/no-explicit-any": ["off"],
            "@typescript-eslint/no-inferrable-types": ["off"],
            "@typescript-eslint/no-empty-function": ["off"],

            "@typescript-eslint/no-unused-vars": ["warn", {
                argsIgnorePattern: "^_",
            }],

            "no-mixed-spaces-and-tabs": ["off"],
            "@typescript-eslint/explicit-module-boundary-types": ["off"],
            "@typescript-eslint/no-non-null-assertion": ["off"],
            "array-callback-return": ["off"],
            "arrow-body-style": ["off"],
            "block-scoped-var": ["warn"],
            camelcase: ["warn"],
            "capitalized-comments": ["off"],
            "class-methods-use-this": ["off"],
            complexity: ["off"],
            "consistent-return": ["off"],
            "consistent-this": ["off"], // TODO
            curly: ["warn"],
            "default-case": ["off"],
            "default-case-last": ["warn"],
            "default-param-last": ["off"],
            "dot-notation": ["off"],
            eqeqeq: ["warn"],
            "func-name-matching": ["warn"],
            "func-names": ["warn"],
            "no-fallthrough": ["off"],
            "grouped-accessor-pairs": ["warn"],
            "guard-for-in": ["off"],
            "id-denylist": ["warn"],
            "id-length": ["off"],
            "id-match": ["warn"],
            "init-declarations": ["off"],
            "max-classes-per-file": ["off"],
            "max-depth": ["off"],
            "max-lines": ["off"],
            "max-lines-per-function": ["off"],
            "max-nested-callbacks": ["off"],
            "max-params": ["off"],
            "max-statements": ["off"],
            "new-cap": ["off"],
            "no-alert": ["warn"],
            "no-array-constructor": ["warn"],
            "no-await-in-loop": ["off"],
            "no-bitwise": ["warn"],
            "no-caller": ["warn"],
            "no-case-declarations": ["off"],
            "no-cond-assign": ["off"],
            "no-confusing-arrow": ["off"],
            "no-console": ["off"],
            "no-constructor-return": ["warn"],
            "no-continue": ["off"],
            "no-control-regex": ["off"],
            "no-div-regex": ["warn"],
            "no-duplicate-imports": ["warn"],
            "no-else-return": ["off"],
            "no-empty": ["off"],
            "no-empty-function": ["off"],
            "no-eq-null": ["warn"],
            "no-eval": ["warn"],
            "no-extend-native": ["warn"],
            "no-extra-boolean-cast": ["off"],
            "no-extra-bind": ["warn"],
            "no-extra-label": ["off"],
            "no-ex-assign": ["off"],
            "no-implicit-coercion": ["off"],
            "no-implicit-globals": ["warn"],
            "no-implied-eval": ["warn"],
            "no-inline-comments": ["off"],
            "no-invalid-this": ["off"],
            "no-iterator": ["warn"],
            "no-label-var": ["warn"],
            "no-labels": ["off"],
            "no-lone-blocks": ["warn"],
            "no-lonely-if": ["warn"],
            "no-loop-func": ["warn"],
            "no-loss-of-precision": ["warn"],
            "no-magic-numbers": ["off"],
            "no-multi-assign": ["warn"],
            "no-multi-str": ["warn"],
            "no-negated-condition": ["off"],
            "no-nested-ternary": ["off"],
            "no-new": ["warn"],
            "no-new-func": ["warn"],
            "no-new-wrappers": ["warn"],
            "no-nonoctal-decimal-escape": ["warn"],
            "no-octal-escape": ["warn"],
            "no-param-reassign": ["off"],
            "no-plusplus": ["off"],
            "no-promise-executor-return": ["off"],
            "no-proto": ["warn"],
            "no-prototype-builtins": ["off"],
            "no-constant-condition": ["off"],
            "no-restricted-exports": ["warn"],
            "no-restricted-globals": ["warn"],
            "no-restricted-imports": ["warn"],
            "no-restricted-properties": ["warn"],
            "no-restricted-syntax": ["warn"],
            "no-return-assign": ["off"],
            "no-script-url": ["warn"],
            "no-self-compare": ["warn"],
            "no-sequences": ["warn"],
            "no-shadow": ["off"],
            "no-template-curly-in-string": ["warn"],
            "no-ternary": ["off"],
            "no-throw-literal": ["warn"],
            "no-undef-init": ["warn"],
            "no-undefined": ["off"],
            "no-underscore-dangle": ["off"],
            "no-unmodified-loop-condition": ["off"],
            "no-unneeded-ternary": ["warn"],
            "no-unreachable-loop": ["warn"],
            "no-unused-expressions": ["warn"],
            "no-use-before-define": ["off"],
            "no-useless-backreference": ["warn"],
            "no-useless-call": ["warn"],
            "no-useless-computed-key": ["warn"],
            "no-useless-concat": ["warn"],
            "no-useless-escape": ["off"],
            "no-useless-constructor": ["off"],
            "no-useless-rename": ["warn"],
            "no-useless-return": ["warn"],
            "no-var": ["warn"],
            "no-void": ["warn"],
            "no-warning-comments": ["off"],
            "object-shorthand": ["warn"],
            "one-var": ["off"],
            "one-var-declaration-per-line": ["off"],
            "operator-assignment": ["warn"],
            "prefer-arrow-callback": ["warn"],
            "prefer-const": ["off"],
            "prefer-destructuring": ["off"],
            "prefer-exponentiation-operator": ["warn"],
            "prefer-named-capture-group": ["off"],
            "prefer-numeric-literals": ["warn"],
            "prefer-object-spread": ["warn"],
            "prefer-promise-reject-errors": ["off"],
            "no-async-promise-executor": ["off"],
            "prefer-regex-literals": ["warn"],
            "prefer-rest-params": ["warn"],
            "prefer-spread": ["warn"],
            "prefer-template": ["off"],
            "quote-props": ["off"],
            radix: ["off"],
            "require-atomic-updates": ["off"],
            "require-await": ["off"],
            "require-unicode-regexp": ["off"],
            strict: ["warn"],
            "symbol-description": ["warn"],
            "vars-on-top": ["warn"],
            yoda: ["warn"],
        },
    }
);